run-dist:
	./build/install/app/bin/app
lint:
	./gradlew checkstyleMain
lint-test:
	./gradlew checkstyleTest
clean:
	./gradlew clean
build:
	./gradlew build
test-coverage:
	./gradlew jacocoTestCoverage